# BEGIN_KITTY_THEME
# Adwaita dark
include current-theme.conf
# END_KITTY_THEME

# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMono Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS

font_size 13.5

enable_audio_bell no

dynamic_background_opacity true
background_blur 0
window_border_width 0

map ctrl+shift+n set_background_opacity +0.1
map ctrl+shift+m set_background_opacity -0.1
map ctrl+shift+a set_background_opacity 1
