general {
    col.active_border = rgb(333333)
    col.inactive_border = rgb(333333)
}

group {
    col.border_active = rgb(CCCCCC)
    col.border_inactive = rgb(333333)

    groupbar {
        col.active = rgb(CCCCCC)
        col.inactive = rgb(333333)

        text_color = rgb(FFFFFF)
        text_color_inactive = rgb(FFFFFF)
    }
}
