general {
    col.active_border = rgb(CCCCCC)
    col.inactive_border = rgb(CCCCCC)
}

#group {
#    col.border_active = rgb(FF4500)
#    col.border_inactive = rgb(CCCCCC)
#
#    groupbar {
#        col.active = rgb(FF4500)
#        col.inactive = rgb(CCCCCC)
#
#        text_color = rgb(FFFFFF)
#        text_color_inactive = rgb(333333)
#    }
#}
