general {
    col.active_border = rgb(CCCCCC)
    col.inactive_border = rgb(CCCCCC)
}

group {
    col.border_active = rgb(CCCCCC)
    col.border_inactive = rgb(CCCCCC)

    groupbar {
        col.active = rgb(333333)
        col.inactive = rgb(CCCCCC)
    }
}