# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = false

format = '''
[](bold #ff0000) $directory ([\[ $git_branch (- $git_status )\]](bold white))
[>](bold white) '''

[directory]
format = '[$path]($style)'
style = "bold white"

[git_branch]
format = "[$symbol $branch(:$remote_branch)]($style)"
symbol = ""
style = "bold red"

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'
