$font = JetBrains Mono Nerd Font Mono

general {
    hide_cursor = true
}

animations {
    enabled = false
}

background {
    monitor =
    path = $HOME/pictures/wallpapers/shd-smaller.png
    blur_passes = 0
}

input-field {
    monitor =
    size = 20%, 5%
    outline_thickness = 8
    inner_color = rgba(0, 0, 0, 0.0) # no fill

    outer_color = rgba(ff6a13ff)
    check_color = rgba(00ff99ee) rgba(ff6633ee) 120deg
    fail_color = rgba(ff0000ff)
    rounding = 0

    font_color = rgb(ffffff)
    fade_on_empty = false

    font_family = $font
    placeholder_text = AUTHENTICATE
    fail_text = $PAMFAIL$FPRINTFAIL

    # uncomment if you wish to display a message during authentication
    # check_text = Authenticating...

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_text_format = 
    # dots_size = 0.4
    dots_spacing = 0.8

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    position = 0, 50
    halign = center
    valign = bottom
}
